//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionHoursLosses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_LOSSES
    {
        public int ID { get; set; }
        public int DETAIL_ID { get; set; }
        public int LOSSES_ID { get; set; }
        public int HRS { get; set; }
    
        public virtual DETAIL DETAIL { get; set; }
        public virtual LOSSES LOSSES { get; set; }
    }
}
