//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionHoursLosses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HEADER()
        {
            this.DETAIL = new HashSet<DETAIL>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATE { get; set; }
        public int FACTORY_ID { get; set; }
        public int ROOM_ID { get; set; }
        public Nullable<int> AVAIL_HRS { get; set; }
        public int STATUS_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL> DETAIL { get; set; }
        public virtual FACTORY FACTORY { get; set; }
        public virtual ROOM ROOM { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
