//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionHoursLosses.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRD_HRS_DBEntities : DbContext
    {
        public PRD_HRS_DBEntities()
            : base("name=PRD_HRS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DETAIL> DETAIL { get; set; }
        public virtual DbSet<DETAIL_LOSSES> DETAIL_LOSSES { get; set; }
        public virtual DbSet<FACTORY> FACTORY { get; set; }
        public virtual DbSet<HEADER> HEADER { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<LOSSES> LOSSES { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<ROOM> ROOM { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
    }
}
